### ISSUE TITLE
`round::half_to_even(1.015, 2)` is not returning `1.02`

### ISSUE THREAD

**Issue by munckymagik** [scoobadog/libmath-rs#7]
Hi

Really useful looking library 👍 . I just tried using it in a personal project and stumbled across the following possible bug.

`round::half_to_even(1.015, 2)` is returning `1.01` not `1.02` as I would expect.

I added the following tests in a local clone to demonstrate the problem. Test 60 fails, even though test 57 is fine.

```rust
// in round.rs
// ...
half_to_even_56: (1.14, 1, 1.1), // ✅ 
half_to_even_57: (1.15, 1, 1.2), // ✅ 
half_to_even_58: (1.16, 1, 1.2), // ✅ 
half_to_even_59: (1.014, 2, 1.01), // ✅ 
half_to_even_60: (1.015, 2, 1.02), // ❌  => 1.01
half_to_even_61: (1.016, 2, 1.02), // ✅ 
// ...
```

Any idea why?

**Comment by scoobadog** [comment]
Hi,

This happens because of 1.015 cannot be represented accurately as a floating point value. I foolishly thought that I had taken this into account but it seems not. The same thing should happen with all of the rounding functions as the issue is actually in `significant_digits` function. I'll add your test case and implement a fix later this week.
